/* Menus Generated by Mega Donkey Menu Designer
   This code includes a main function
*/

#include "donkey.h"


// forward declarations of all menu functions 
void menu_main(void);
void menu_cal(void);
void menu_drive(void);

// Slider Variables and CheckBox variables

// menu_cal variables
   int Kp = 50;
   int Ki = 50;
   int Kd = 50;
   int Km = 50;
   int Ka = 50;

// menu_drive variables
   u08 light = 1;
   int vel = 50;


void menu_main (void)
{

   MENU_INIT
   do {
      MENU_CONTROLS

      menu_label(11,2,"Main Menu");   // x,y,text 
      menu_button(12,24,"CALIBRATION",1); // x,y,name,response
      menu_button(12,39,"DRIVE",2); // x,y,name,response
      menu_exitbutton();

      // optional non-menu code here

      MENU_COMMANDS

      switch (menu_cmd()) {

         case 1 : // CALIBRATION Button Response Code
           menu_call(menu_cal);
            
            break;
         case 2 : // DRIVE Button Response Code
           menu_call(menu_drive);
            
            break;

      }
   } while (menu_cmd() != MENU_EXITCODE); // loop until [X] Exit 

   wait_while_touched();   // optional

} // end menu 


void menu_cal (void)
{

   MENU_INIT
   do {
      MENU_CONTROLS

      // Horizontal Slider  x,y,width,label,VarName,min,max,show value,response
      menu_slider(24,21,50,"P",Kp,0,100,1,1);
      
      // Horizontal Slider  x,y,width,label,VarName,min,max,show value,response
      menu_slider(24,31,51,"I",Ki,0,100,1,2);
      
      // Horizontal Slider  x,y,width,label,VarName,min,max,show value,response
      menu_slider(24,41,50,"D",Kd,0,100,1,3);
      
      // Horizontal Slider  x,y,width,label,VarName,min,max,show value,response
      menu_slider(24,51,50,"M",Km,0,100,1,4);
      
      // Horizontal Slider  x,y,width,label,VarName,min,max,show value,response
      menu_slider(24,61,50,"A",Ka,0,100,1,5);
      
      menu_label(4,3,"CALIBRATION MENU");   // x,y,text 
      menu_exitbutton();

      // optional non-menu code here

      MENU_COMMANDS

      switch (menu_cmd()) {


      }
   } while (menu_cmd() != MENU_EXITCODE); // loop until [X] Exit 

   wait_while_touched();   // optional

} // end menu 


void menu_drive (void)
{

   MENU_INIT
   do {
      MENU_CONTROLS

      menu_buttonrow(26,46,"FLRB Z"); // x,y,buttons  response=char values
      menu_button(51,64,"STOP",1); // x,y,name,response
      if (MenuDraw) box(25,11,110,41); // x1,y1,x2,y2
      menu_checkbox(43,23,"Light",light,2); //  x,y,label,variable,response
      // Vertical Slider  x,y,height,label,VarName,min,max,show value,response
      menu_vslider(135,35,30,"vel",vel,0,100,1,3);
      
      menu_exitbutton();

      // optional non-menu code here

      MENU_COMMANDS

      switch (menu_cmd()) {

         case 'F' : // Button Row Item Response
            break;
         case 'L' : // Button Row Item Response
            break;
         case 'R' : // Button Row Item Response
            break;
         case 'B' : // Button Row Item Response
            break;
         case 'Z' : // Button Row Item Response
            break;
         case 1 : // STOP Button Response Code
            
            break;
         case 2 : // CheckBox Light for light
            // optional response code
            break;

      }
   } while (menu_cmd() != MENU_EXITCODE); // loop until [X] Exit 

   wait_while_touched();   // optional

} // end menu 


int main (void)
{
   md_init();      // Mega Donkey Init 

   printf(" Donkey Wiz Menu:\n"); 
   printf(" Jan 08, 2008\n");
   printf(" 05:00 am\n");
   wait_until_touched();
   lcd_clear();

   menu_main();    // Call Main Menu
   while(1);       // infinite loop (prevent compiler warning / main not allowed to end
}
